name: html to pdf
on: [push]
  uses: fifsky/html-to-pdf-action@master
  with:
    htmlFile: ./index.html
    outputFile: ./resume.pdf
    pdfOptions: '{"format": "A3", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}, "scale": "0.86"}'