name: Build resume
on:
  push:
    tags:
      - "*"
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: src/index.html
          outputFile: src/resume.pdf
          pdfOptions: '{"format": "A3", "scale": 0.80, "margin": {"top": "0", "left": "0", "right": "0", "bottom": "0"}}'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/resume.pdf