name: deploy resume
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./resume.pdf
          pdfOptions: '{"format": "A3", "scale": 0.86, "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
