name: Build resume
on:
  push:
    tags:
      - "*"
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./resume.pdf
          pdfOptions: '{"format": "A3", "scale": 0.86, "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "11mm"}}'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/resume.pdf